### ISSUE TITLE
Chores Page Buttons Not Working

### ISSUE THREAD

**Issue by giulioco** [gcollelu/dirtydish#2]
For some reason, the reference to the buttons relative to the chores page ChoresFragment is null. So, when it goes to bind it with the onClickListener it doesn't actually do anything. Nonetheless, it still displays the buttons..

**Comment by Ormakent** [comment]
Fixed with commit f5f8cb00c7ff22258dff818de0e33983acdb874d
Do not use synthetic views before view is created
